---
title: "Graphs"
author: "Katie Levesque, Meerim Ruslanova, Sarah Unbehaun"
date: "May 8, 2016"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r datasource, include=FALSE, cache.extra=list(file.info("~/Climate-Happiness/Data/All_Merged_Data.csv")$mtime)}
setwd('~/GitHub/Climate-Happiness')
source('~/GitHub/Climate-Happiness/Data/SourceFile.R')
data <- read.csv("All_Merged_Data.csv")
attach(data)
```

```{r, echo=FALSE}

#Boxplot of emissions levels by state
ggplot(data, aes(x=State, y=Emissions), main = "Emissions by State", xlab = "State", ylab = "Emissions (annual tons of CO2 per capita)") +geom_boxplot(aes(fill=factor(State))) + scale_colour_discrete() + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + guides(fill=FALSE)
```

```{r, echo=FALSE}
# Line graph of emissions levels by state over time
ggplot(data, aes(x = Year, y = Emissions, group = State, color = State)) + geom_line() + scale_colour_discrete() +labs(y = "Emissions (annual tons of CO2 per capita)")
```

``` {r set plot function, echo=FALSE, include=FALSE}
multiplot <- function(..., plotlist = NULL, file, cols = 1, layout = NULL) {
  require(grid)

  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  if (is.null(layout)) {
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

  if (numPlots == 1) {
    print(plots[[1]])

  } else {
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    for (i in 1:numPlots) {
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r, echo=FALSE}
#Boxplot of life satisfaction by state 
ggplot(data, aes(x=State, y=satis), main = "Average Life Satisfaction by State", xlab = "State", ylab = "Satisfaction") +geom_boxplot(aes(fill=factor(State))) + scale_colour_discrete() + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + guides(fill=FALSE)
```

```{r, echo=FALSE}
aggremeans <- aggregate(data[, c(1, 3, 6, 18, 19, 22)], list(State, Year), mean)
ggplot(aggremeans, aes(x = Year, y = satis, group = Group.1, color = Group.1)) + geom_line() + scale_colour_discrete() +labs(y = "Life Satisfaction")
```

```{r scatterplots, echo=FALSE}
# scatterplots of aggregate state satisfaction over years
plot1 <- ggplot(data = aggremeans, aes(x=age, y=satis)) + geom_point() +geom_smooth() + labs(x = "Age", y = "Life Satisfaction")
plot2 <- ggplot(data = aggremeans, aes(x=Emissions, y=satis)) + geom_point() +geom_smooth() + labs(x = "Emissions per Capita", y = "Life Satisfaction")
plot3 <- ggplot(data = aggremeans, aes(x=Use, y=satis)) + geom_point() +geom_smooth() + labs(x = "Energy Use per Capita", y = "Life Satisfaction")
plot4 <- ggplot(data = aggremeans, aes(x=environ, y=satis)) + geom_point() +geom_smooth() + labs(x = "Concern about the Environment", y = "Life Satisfaction")
multiplot(plot1, plot2, plot3, plot4, cols=2)
```