---
title: "Research Proposal: Do emissions affect life satisfaction?"
author: "Katie Levesque, Meerim Ruslanova, Sarah Unbehaun"
date: "March 21, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
Climate change is undoubtedly a global problem, but this fact means it is also, 
in a way, a classic tragedy of the commons. No country wants to put itself at an
economic disadvantage by restricting the use of cheap fossil fuels, deteriorating 
the "commons" of the Earth's protective atmosphere. This can make it difficult to
get citizens to identify with the problem and take responsibility; people will 
more likely act when something affects them individually. In this paper we want 
to explore this aspect: how much do people feel, consciously or unconsciously, 
the effects of green house gas emissions? More specifically, do emissions affect 
their reported health, well-being, or life satisfaction? This leads to our general 
hypothesis: 

To examine this question, we will look at data from Germany. Germany is a leader
in protecting the environment while also having a long history as an industrial
power and coal producer. Its *Energiewende* (energy transition) is considered 
one of the most ambitious climate policy projects in the world. On the other 
hand, it has struggled with appropriate incentives, a drop in oil prices (not to
mention coal's continued role as a cheap and reliable fuel) and how to transform 
the transportation sector. Germany therefore still does emit large amounts of 
green house gases. We will look at green house gas emissions data by *Bundesland* 
(federal state) and compare that with life satisfaction data to examine our first
hypothesis:

> *H1: Bundeslaender with higher emissions will have lower reported levels of 
health, well-being, or life satisfaction.* 

We will also investigate whether there is a time component to perceptions of life
satisfaction and well-being. Using data going back to 1990, and again using 
emissions as the independent variable of primary interest, our second hypothesis 
is:

> *H2: Do emissions play a role in how reported levels of health, well-being, or 
life satisfaction have changed over time?*



## Literature Review


## Bibliography

