---
title: "Analysis"
author: "Katie Levesque, Sarah Unbehaun, Meerim Ruslanova"
date: "April 14, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("SourceFile.R")
```


```{r, include=FALSE}
data <- read.csv("All_Merged_Data.csv")
attach(data)
```

Basic statistics

```{r, echo=FALSE}
aggregate(formula=Satisfaction~Emissions+Year+State, data=data, FUN=mean)

data[data$State=="Berlin", ]
```

```{r, echo=FALSE}

#Boxplot of emissions levels by state
names(data)
data.frame(data)
boxplot(emissions~State,
  data=data,
  main="Emissions by State",
  xlab="State",
  ylab="Emissions",
  col="royalblue1",
  border="royalblue4"
)
```

```{r, echo=FALSE}
#Boxplot of life satisfaction by state
boxplot(satis~State,
  data=data,
  main="Satisfaction by State",
  xlab="State",
  ylab="Satisfaction (1-10)",
  col="royalblue1",
  border="royalblue4"
)
```

```{r, echo=FALSE}
qplot(data$State, data$Emissions, geom = "boxplot", main = "Emissions by State", xlab = "State", ylab = "Emissions", fill = factor(data$State)) + guides(fill=FALSE)
```

```{r, echo=FALSE}
library(foreign)
library(car)
#panel data scatterplot of aggregate state satisfaction over years
scatterplot(Satisfaction~Year|State, boxplots=FALSE, smooth=TRUE, reg.line=FALSE, data=Panel)
```


```{r, echo=FALSE}
##Regression using individual level data

#Declare X and Y variables for panel data
Y1<-cbind(satis_labels)
X1<-cbind(emissions, Use, concerned)

#set data as panel data
pdataind<-plm.data(data, index=c("PID","Year"))

summary(X1)
summary(Y1)

#pooled OLS estimator
poolingind<-plm(Y1~X1, data=pdataind, model="pooling")
summary(pooling)

#between estimator
betweenind<-plm(Y1~X1, data=pdataind, model="between")
summary(between)

#first difference estimator
firstdiffind<-plm(Y1~X1, data=pdataind, model="fd")
summary(firstdiff)

#fixed effects or within estimator
within<-plm(Y1~X1, data=pdataind, model="within")

#LM test for fixed effects vs OLS
pFtest(fixed,pooling)
```

```{r descr, echo=FALSE}
##Regression using State level data

#Declare X and Y variables for panel data
Y2<-cbind(satis_labels)
X2<-cbind(emissions, Use, concerned)

#set data as panel data
pdatastate<-plm.data(data, index=c("State","Year"))

summary(X2)
summary(Y2)

#pooled OLS estimator
poolingstate<-plm(Y2~X2, data=pdatastate, model="pooling")
summary(poolingstate)

#between estimator
betweenstate<-plm(Y2~X2, data=pdatastate, model="between")
summary(betweenstate)

#first difference estimator
firstdiffstate<-plm(Y2~X2, data=pdatastate, model="fd")
summary(firstdiffstate)

#fixed effects or within estimator
withinstate<-plm(Y2~X2, data=pdatastate, model="within")
summary(withinstate)

#LM test for fixed effects vs OLS
pFtest(fixed,pooling)

#Likelihood ratio test determining which model fits better
lrtest(fixed,pooling)  
```

