---
title: "Assignment #3"
author: "Katie Levesque, Sarah Unbehaun, Meerim Ruslanova"
date: "April 14, 2016"
output: html_document
---

```{r, include=FALSE}
setwd('~/GitHub/Climate-Happiness/Data')
source('~/GitHub/Climate-Happiness/Data/SourceFile.R')
data <- read.csv("All_Merged_Data.csv")
attach(data)
```

Basic statistics

```{r, echo=FALSE}
summary(State)

aggregate(formula=satis_labels~Emissions+Year+State, data=data, FUN=mean)

data[data$State=="Berlin", ]
```

```{r, echo=FALSE}

#Boxplot of emissions levels by state
names(data)
data.frame(data)
boxplot(Emissions~LandCode,
  data=data,
  main="Emissions by State",
  xlab="State",
  ylab="Emissions (annual tons of CO2 per capita)",
  col="royalblue1",
  border="royalblue4"
)
```

```{r, echo=FALSE}
# Line graph of emissions levels by state over time
ggplot(data, aes(x = Year, y = Emissions, group = State, color = State)) + geom_line() + scale_colour_discrete() +labs(y = "Emissions (annual tons of CO2 per capita)")
```

```{r, echo=FALSE}
#Boxplot of life satisfaction by state
boxplot(satis~State,
  data=data,
  main="Satisfaction by State",
  xlab="State",
  ylab="Satisfaction (1-4)",
  col="royalblue1",
  border="royalblue4"
)
```

```{r, echo=FALSE}
qplot(data$State, data$Emissions, geom = "boxplot", main = "Emissions by State", xlab = "State", ylab = "Emissions", fill = factor(data$State)) + guides(fill=FALSE)
```

```{r, echo=FALSE}

#panel data scatterplot of aggregate state satisfaction over years
scatterplot(satis~Year|State, boxplots=FALSE, smooth=TRUE, reg.line=FALSE, data=data)
```


```{r, echo=FALSE}
##Regression using individual level data

#Declare X and Y variables for panel data
Y1<-cbind(satis_labels)
X1<-cbind(Emissions, Use, environ, gender, age)

#set data as panel data
pdataind<-plm.data(data, index=c("pid","Year"))

summary(X1)
summary(Y1)

#pooled OLS estimator
L1<-plm(Y1~X1, data=pdataind, model="pooling")
summary(L1)

#between estimator
L2<-plm(Y1~X1, data=pdataind, model="between")
summary(L2)

#first difference estimator
L3<-plm(Y1~X1, data=pdataind, model="fd")
summary(L3)

#fixed effects or within estimator
L4<-plm(Y1~X1, data=pdataind, model="within")
summary(L4)

#LM test for fixed effects vs OLS
pFtest(L2,L1)

library(stargazer)
stargazer(L1, L2, L3, L4,
    title = 'Regression Estimates of Life Satisfaction',
    digits = 2, type = 'html'
    )
```

```{r, echo=FALSE}
##Regression using State level data

#Declare X and Y variables for panel data
Y2<-cbind(satis_labels)
X2<-cbind(Emissions, Use, environ, gender, age)

#set data as panel data
pdatastate<-plm.data(data, index=c("State","Year"))

summary(X2)
summary(Y2)

#pooled OLS estimator
L5<-plm(Y2~X2, data=pdatastate, model="pooling")
summary(L5)

#between estimator
L6<-plm(Y2~X2, data=pdatastate, model="between")
summary(L6)

#first difference estimator
L7<-plm(Y2~X2, data=pdatastate, model="fd")
summary(L7)

#fixed effects or within estimator
L8<-plm(Y2~X2, data=pdatastate, model="within")
summary(L8)

#LM test for fixed effects vs OLS
pFtest(L5,L6)

#Likelihood ratio test determining which model fits better
lrtest(fixed,pooling) 

stargazer(L5, L6, L7, L8,
    title = 'Regression Estimates of Life Satisfaction',
    digits = 2, type = 'html'
    )
```

```{r descr, echo=FALSE}
#Find the range pf emissions values to create a 95% confidence interval for between regression
range(satis)
Satisfaction_range<-1:4

#extract point estimates and co-variance matrix
L2_coef <- matrix(coef(L2))
L2_vcov <- vcov(L2)

#draw 1000 simulations of the point estimates
library(MASS) # contains the mvrnorm function
drawn <- mvrnorm(n = 1000, mu = L2_coef, Sigma = L2_vcov) %>% 
            data.frame
head(drawn)[1:3, ]

drawn_sim <- merge(drawn, Satisfaction_range)

# Rename the fitted value variable
drawn_sim <- dplyr::rename(drawn_sim, fitted_satisfaction = y)

nrow(drawn)
nrow(drawn_sim)

#calculate the quantity of interest 
names(drawn_sim)
drawn_sim$sim_wc <- drawn_sim[, 1] + drawn_sim[, 2] * drawn_sim[, 5] + 
                        drawn_sim[, 3]

#plot points
ggplot(drawn_sim, aes(fitted_satisfaction, sim_wc)) + 
        geom_point(alpha = 0.2) + stat_smooth(se = FALSE) +
        theme_bw()

# Find 95% central interval and median at each fitted value of edu
central <- drawn_sim %>% group_by(fitted_satisfaction) %>%
            summarise(median_sim = median(sim_wc),
                      lower_95 = quantile(sim_wc, probs = 0.025),
                      upper_95 = quantile(sim_wc, probs = 0.975)
            )

#plot 95% confidence interval
ggplot(central, aes(fitted_satisfaction, median_sim)) +
    geom_ribbon(aes(ymin = lower_95, ymax = upper_95), alpha = 0.3) +
    geom_line() + theme_bw()

```