---
title: "GSOEP Codebook of Variables"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Variables to Request



# ID
 Pid Never Changing Person ID [pid] 


# Life satisfaction
   p11101Overall life satisfaction [p11101]  
Variable in study: soep-long | dataset: pequiv | period: long | analysis unit: p | concept: _pequiv_p11101
   plh0182Current Life Satisfaction [plh0182]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pzule1
   plh0151Satisfaction With Life Today [plh0151]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: plh0151
   plh0180satisfaction with family life [plh0180]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pzuf13
   plh0181Satisfaction With Social Life [plh0181]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pzuf14
   plh0183Satisfaction With Life Five Years From Now [plh0183]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pzule2
   plh0149Satisfaction With Life Five Years Ago [plh0149]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: plh0149
   plh0150Satisfaction With Life A Year Ago [plh0150]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: _1556_p_sat
   plh0166Satisfaction With Life A Year From Now [plh0166]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pzule3
   plh0273Satisfaction With Life Past 10 Year [plh0273]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept:
   plh0274Satisfaction With Life In Next Five Years [plh0274]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept:


# Education	
 d11109Number of Years of Education [d11109]  
Variable in study: soep-long | dataset: pequiv | period: long | analysis unit: p | concept: _pequiv_d11109
 pgbilztchChange in Education since last survey / last year [pgbilztch]  
Variable in study: soep-long | dataset: pgen | period: long | analysis unit: p | concept: _pgen_pgbilztch
   plc0004Income Corresponds To Education [plc0004]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: plc0004
   plb0063Currently In Education, Training [plb0063]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pazubi
   plg0103No Money For Further Education [plg0103]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pwb11
   plb0073Training Required [plb0073]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pberaus
   plg0037School-Leaving Degree [plg0037]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pabs02
   plg0016Now College [plg0016]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: paus4


# Health
   ple0008Current Health [ple0008]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pges01
   m11121Health limits vigorous activities [m11121]  
Variable in study: soep-long | dataset: pequiv | period: long | analysis unit: p | concept: _pequiv_m11121
   m11125Satisfaction with Health [m11125]  
Variable in study: soep-long | dataset: pequiv | period: long | analysis unit: p | concept: _pequiv_m11125
   plh0171Satisfaction With Health [plh0171]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pzuf01
   plh0099Import.-Health For Satisfaction [plh0099]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: _166_p_ila
  ple0095 Follows Health-conscious Diet [ple0095]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pessen


# Employment
   plb0111Reason For Employment [plb0111]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pnerw06
 plb0022Employment Status [plb0022]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: perw
   ple0040Legally Handicapped, Reduced Employment [ple0040]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pbeh1
   l0266Last Year Of Employment [l0266]  
Variable in study: soep-long | dataset: bio | period: long | analysis unit: p | concept: l0266
  pgexpft Working Experience Full-Time Employment [pgexpft]  
Variable in study: soep-long | dataset: pgen | period: long | analysis unit: p | concept: _pgen_pgexpft
  iunby Unemployment benefit [iunby]  
Variable in study: soep-long | dataset: pequiv | period: long | analysis unit: p | concept: _pequiv_iunby 

or

  iunay Unemployment assistance [iunay]  
Variable in study: soep-long | dataset: pequiv | period: long | analysis unit: p | concept: _pequiv_iunay
  pgstib Occupational Position [pgstib]  
Variable in study: soep-long | dataset: pgen | period: long | analysis unit: p | concept: _pgen_pgstib


# Income
   plc0004Income Corresponds To Education [plc0004]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: plc0004
   plb0228Income Is Sufficient [plb0228]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: _1448_p_whb
   plh0176Satisfaction With Personal Income [plh0176]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pzuf05
   pglabnetCurrent Net Labor Income in Euro [pglabnet]  
Variable in study: soep-long | dataset: pgen | period: long | analysis unit: p | concept: _pgen_pglabnet
   plh0141do not Know Amount of Fair Net Income [plh0141]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: precht03
   plc0014Net Income Last Month [plc0014]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pnett


# Sex
   d11102llGender of Individual [d11102ll]  
Variable in study: soep-long | dataset: pequiv | period: long | analysis unit: p | concept: _pequiv_d11102ll


# Bundesland
l11101 State of Residence [l11101]  
Variable in study: soep-long | dataset: pequiv | period: long | analysis unit: p | concept: _pequiv_l11101


# Age
   d11101Age of Individual [d11101]  
Variable in study: soep-long | dataset: pequiv | period: long | analysis unit: p | concept: _pequiv_d11101
   plc0113Financial Secure In Old Age [plc0113]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: psoz3
   plc0114Financial Secure In Old Age [plc0114]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: psoz4


# Country of origin
   coriginCountry Of Origin [corigin]  
Variable in study: soep-long | dataset: ppfad | period: long | analysis unit: p | concept: corigin
   plj0080Connected With Country Of Origin [plj0080]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pna15
   plj0182Feel At Home In Country Of Origin [plj0182]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept:
   plj0141Spouse Lives In Foreign Country [plj0141]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: punt34
   ypnatNationality [ypnat]  
Variable in study: soep-long | dataset: pbr_exit | period: long | analysis unit: p | concept: ypnat


# Marital status
   pgfamstdMarital Status [pgfamstd]  
Variable in study: soep-long | dataset: pgen | period: long | analysis unit: p | concept: _pgen_pgfamstd


# Children
   hlc0043Number Children [hlc0043]  
Variable in study: soep-long | dataset: hl | period: long | analysis unit: h | concept: hdkg3
   l0047Family Abroad: Children [l0047]  
Variable in study: soep-long | dataset: bio | period: long | analysis unit: p | concept: l0047
   plh0110Importance: To have children [plh0110]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pwich7


# Environment
plh0160 Satisfaction With Environment [plh0160]  	(limited years/responses) 
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: pzuf15 
plh0036 Worried About Environment [plh0036]  
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: psor04
plh0037 worried about consequences from climate change [plh0037] 	(also limited years) 
Variable in study: soep-long | dataset: pl | period: long | analysis unit: p | concept: psor14
1

